// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// @skip-file-minify - Skip attempting to minify this file

import { createEnumMap } from "../JavaScriptSDK.Enums/EnumHelperFuncs";
import {
    strAddNotificationListener, strAddPlugin, strAddTelemetryInitializer, strAddUnloadCb, strConfig, strDiagLog,
    strEventsDiscarded, strEventsSendRequest, strEventsSent, strEvtNamespace, strGetCookieMgr, strGetNotifyMgr,
    strGetPerfMgr, strGetPlugin, strGetProcessTelContext, strGetTransmissionControls, strIdentifier, strInitialize,
    strIsInitialized, strLogger, strPerfEvent, strPollInternalLogs, strPriority, strProcessTelemetry,
    strRemoveNotificationListener, strResume, strSetCookieMgr, strSetInitialized, strSetNextPlugin, strSetPerfMgr,
    strStopPollingInternalLogs, strTeardown, strUnload, strUpdate, strUpdateCfg, str_DoTeardown, str_DoUpdate, str_GetTelCtx
} from "../JavaScriptSDK/InternalConstants";


export const enum eSdkCoreNames {
    initialize = 0,
    isInitialized = 1,
    processTelemetry = 2,
    config = 3,
    logger = 4,
    identifier = 5,
    getTransmissionControls = 6,
    getNotifyMgr = 7,
    getCookieMgr = 8,
    setCookieMgr = 9,
    addNotificationListener = 10,
    removeNotificationListener = 11,
    addTelemetryInitializer = 12,
    pollInternalLogs = 13,
    stopPollingInternalLogs = 14,
    getProcessTelContext = 15,
    unload = 16,
    getPlugin = 17,
    addPlugin = 18,
    updateCfg = 19,
    evtNamespace = 20,
    addUnloadCb = 21,
    setNextPlugin = 22,
    getPerfMgr = 23,
    setPerfMgr = 24,
    teardown = 25,
    update = 26,
    priority = 27,
    resume = 28,
    _doTeardown = 29,
    _getTelCtx = 30,
    setInitialized = 31,
    diagLog = 32,
    _doUpdate = 33,
    eventsSent = 34,
    eventsDiscarded = 35,
    eventsSendRequest = 36,
    perfEvent = 37,
}

export const SdkCoreNames = createEnumMap<typeof eSdkCoreNames, {
    [eSdkCoreNames.initialize]: "initialize",
    [eSdkCoreNames.isInitialized]: "isInitialized",
    [eSdkCoreNames.processTelemetry]: "processTelemetry",
    [eSdkCoreNames.config]: "config",
    [eSdkCoreNames.logger]: "logger",
    [eSdkCoreNames.identifier]: "identifier",
    [eSdkCoreNames.getTransmissionControls]: "getTransmissionControls",
    [eSdkCoreNames.getNotifyMgr]: "getNotifyMgr",
    [eSdkCoreNames.getCookieMgr]: "getCookieMgr",
    [eSdkCoreNames.setCookieMgr]: "setCookieMgr",
    [eSdkCoreNames.addNotificationListener]: "addNotificationListener",
    [eSdkCoreNames.removeNotificationListener]: "removeNotificationListener",
    [eSdkCoreNames.addTelemetryInitializer]: "addTelemetryInitializer",
    [eSdkCoreNames.pollInternalLogs]: "pollInternalLogs",
    [eSdkCoreNames.stopPollingInternalLogs]: "stopPollingInternalLogs",
    [eSdkCoreNames.getProcessTelContext]: "getProcessTelContext",
    [eSdkCoreNames.unload]: "unload",
    [eSdkCoreNames.getPlugin]: "getPlugin",
    [eSdkCoreNames.addPlugin]: "addPlugin",
    [eSdkCoreNames.updateCfg]: "updateCfg",
    [eSdkCoreNames.evtNamespace]: "evtNamespace",
    [eSdkCoreNames.addUnloadCb]: "addUnloadCb",
    [eSdkCoreNames.setNextPlugin]: "setNextPlugin",
    [eSdkCoreNames.getPerfMgr]: "getPerfMgr",
    [eSdkCoreNames.setPerfMgr]: "setPerfMgr",
    [eSdkCoreNames.teardown]: "teardown",
    [eSdkCoreNames.update]: "update",
    [eSdkCoreNames.priority]: "priority",
    [eSdkCoreNames.resume]: "resume",
    [eSdkCoreNames._doTeardown]: "_doTeardown",
    [eSdkCoreNames._getTelCtx]: "_getTelCtx",
    [eSdkCoreNames.setInitialized]: "setInitialized",
    [eSdkCoreNames.diagLog]: "diagLog",
    [eSdkCoreNames._doUpdate]: "_doUpdate",
    [eSdkCoreNames.eventsSent]: "eventsSent",
    [eSdkCoreNames.eventsDiscarded]: "eventsDiscarded",
    [eSdkCoreNames.eventsSendRequest]: "eventsSendRequest",
    [eSdkCoreNames.perfEvent]: "perfEvent"
}>({
    [strInitialize]: eSdkCoreNames.initialize,
    [strIsInitialized]: eSdkCoreNames.isInitialized,
    [strProcessTelemetry]: eSdkCoreNames.processTelemetry,
    [strConfig]: eSdkCoreNames.config,
    [strLogger]: eSdkCoreNames.logger,
    [strIdentifier]: eSdkCoreNames.identifier,
    [strGetTransmissionControls]: eSdkCoreNames.getTransmissionControls,
    [strGetNotifyMgr]: eSdkCoreNames.getNotifyMgr,
    [strGetCookieMgr]: eSdkCoreNames.getCookieMgr,
    [strSetCookieMgr]: eSdkCoreNames.setCookieMgr,
    [strAddNotificationListener]: eSdkCoreNames.addNotificationListener,
    [strRemoveNotificationListener]: eSdkCoreNames.removeNotificationListener,
    [strAddTelemetryInitializer]: eSdkCoreNames.addTelemetryInitializer,
    [strPollInternalLogs]: eSdkCoreNames.pollInternalLogs,
    [strStopPollingInternalLogs]: eSdkCoreNames.stopPollingInternalLogs,
    [strGetProcessTelContext]: eSdkCoreNames.getProcessTelContext,
    [strUnload]: eSdkCoreNames.unload,
    [strGetPlugin]: eSdkCoreNames.getPlugin,
    [strAddPlugin]: eSdkCoreNames.addPlugin,
    [strUpdateCfg]: eSdkCoreNames.updateCfg,
    [strEvtNamespace]: eSdkCoreNames.evtNamespace,
    [strAddUnloadCb]: eSdkCoreNames.addUnloadCb,
    [strSetNextPlugin]: eSdkCoreNames.setNextPlugin,
    [strGetPerfMgr]: eSdkCoreNames.getPerfMgr,
    [strSetPerfMgr]: eSdkCoreNames.setPerfMgr,
    [strTeardown]: eSdkCoreNames.teardown,
    [strUpdate]: eSdkCoreNames.update,
    [strPriority]: eSdkCoreNames.priority,
    [strResume]: eSdkCoreNames.resume,
    [str_DoTeardown]: eSdkCoreNames._doTeardown,
    [str_GetTelCtx]: eSdkCoreNames._getTelCtx,
    [strSetInitialized]: eSdkCoreNames.setInitialized,
    [strDiagLog]: eSdkCoreNames.diagLog,
    [str_DoUpdate]: eSdkCoreNames._doUpdate,
    [strEventsSent]: eSdkCoreNames.eventsSent,
    [strEventsDiscarded]: eSdkCoreNames.eventsDiscarded,
    [strEventsSendRequest]: eSdkCoreNames.eventsSendRequest,
    [strPerfEvent]: eSdkCoreNames.perfEvent
});
