"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.stringToBoolOrDefault = exports.EventPersistence = exports.DistributedTracingModes = exports.Extensions = exports.CtxTagKeys = exports.createTelemetryItem = exports.TelemetryItemCreator = exports.dsPadNumber = exports.dataSanitizeInput = exports.dataSanitizeId = exports.dataSanitizeMeasurements = exports.dataSanitizeProperties = exports.dataSanitizeException = exports.dataSanitizeMessage = exports.dataSanitizeUrl = exports.dataSanitizeString = exports.dataSanitizeKey = exports.dataSanitizeKeyAndAddUniqueness = exports.ContextTagKeys = exports.ConfigurationManager = exports.SeverityLevel = exports.Data = exports.PageViewPerformance = exports.Trace = exports.RemoteDependencyData = exports.PageView = exports.Metric = exports.Exception = exports.Event = exports.Envelope = exports.strNotSpecified = exports.DEFAULT_BREEZE_PATH = exports.DEFAULT_BREEZE_ENDPOINT = exports.HttpMethod = exports.SampleRate = exports.ProcessLegacy = exports.DisabledPropertyName = exports.RequestHeaders = exports.ConnectionStringParser = exports.parseConnectionString = exports.ThrottleMgr = exports.createDistributedTraceContextFromTrace = exports.isInternalApplicationInsightsEndpoint = exports.dateTimeUtilsDuration = exports.dateTimeUtilsNow = exports.correlationIdGetCorrelationContextValue = exports.correlationIdGetCorrelationContext = exports.correlationIdCanIncludeCorrelationHeader = exports.correlationIdGetPrefix = exports.correlationIdSetPrefix = void 0;
exports.AnalyticsPluginIdentifier = exports.BreezeChannelIdentifier = exports.PropertiesPluginIdentifier = exports.createOfflineListener = exports.urlParseFullHost = exports.urlParseHost = exports.urlGetCompleteUrl = exports.urlGetPathName = exports.urlGetAbsoluteUrl = exports.urlParseUrl = exports.utlSetStoragePrefix = exports.utlRemoveSessionStorage = exports.utlSetSessionStorage = exports.utlGetSessionStorage = exports.utlGetSessionStorageKeys = exports.utlCanUseSessionStorage = exports.utlRemoveStorage = exports.utlSetLocalStorage = exports.utlGetLocalStorage = exports.utlCanUseLocalStorage = exports.utlEnableStorage = exports.utlDisableStorage = exports.createDomEvent = exports.findAllScripts = exports.findW3cTraceParent = exports.formatTraceParent = exports.isSampledFlag = exports.isValidTraceParent = exports.isValidSpanId = exports.isValidTraceId = exports.parseTraceParent = exports.createTraceParent = exports.ITraceParent = exports.isBeaconApiSupported = exports.isCrossOriginError = exports.getExtensionByName = exports.msToTimeSpan = void 0;
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the
var Util_1 = require("./Util");
Object.defineProperty(exports, "correlationIdSetPrefix", { enumerable: true, get: function () { return Util_1.correlationIdSetPrefix; } });
Object.defineProperty(exports, "correlationIdGetPrefix", { enumerable: true, get: function () { return Util_1.correlationIdGetPrefix; } });
Object.defineProperty(exports, "correlationIdCanIncludeCorrelationHeader", { enumerable: true, get: function () { return Util_1.correlationIdCanIncludeCorrelationHeader; } });
Object.defineProperty(exports, "correlationIdGetCorrelationContext", { enumerable: true, get: function () { return Util_1.correlationIdGetCorrelationContext; } });
Object.defineProperty(exports, "correlationIdGetCorrelationContextValue", { enumerable: true, get: function () { return Util_1.correlationIdGetCorrelationContextValue; } });
Object.defineProperty(exports, "dateTimeUtilsNow", { enumerable: true, get: function () { return Util_1.dateTimeUtilsNow; } });
Object.defineProperty(exports, "dateTimeUtilsDuration", { enumerable: true, get: function () { return Util_1.dateTimeUtilsDuration; } });
Object.defineProperty(exports, "isInternalApplicationInsightsEndpoint", { enumerable: true, get: function () { return Util_1.isInternalApplicationInsightsEndpoint; } });
Object.defineProperty(exports, "createDistributedTraceContextFromTrace", { enumerable: true, get: function () { return Util_1.createDistributedTraceContextFromTrace; } });
var ThrottleMgr_1 = require("./ThrottleMgr");
Object.defineProperty(exports, "ThrottleMgr", { enumerable: true, get: function () { return ThrottleMgr_1.ThrottleMgr; } });
var ConnectionStringParser_1 = require("./ConnectionStringParser");
Object.defineProperty(exports, "parseConnectionString", { enumerable: true, get: function () { return ConnectionStringParser_1.parseConnectionString; } });
Object.defineProperty(exports, "ConnectionStringParser", { enumerable: true, get: function () { return ConnectionStringParser_1.ConnectionStringParser; } });
var RequestResponseHeaders_1 = require("./RequestResponseHeaders");
Object.defineProperty(exports, "RequestHeaders", { enumerable: true, get: function () { return RequestResponseHeaders_1.RequestHeaders; } });
var Constants_1 = require("./Constants");
Object.defineProperty(exports, "DisabledPropertyName", { enumerable: true, get: function () { return Constants_1.DisabledPropertyName; } });
Object.defineProperty(exports, "ProcessLegacy", { enumerable: true, get: function () { return Constants_1.ProcessLegacy; } });
Object.defineProperty(exports, "SampleRate", { enumerable: true, get: function () { return Constants_1.SampleRate; } });
Object.defineProperty(exports, "HttpMethod", { enumerable: true, get: function () { return Constants_1.HttpMethod; } });
Object.defineProperty(exports, "DEFAULT_BREEZE_ENDPOINT", { enumerable: true, get: function () { return Constants_1.DEFAULT_BREEZE_ENDPOINT; } });
Object.defineProperty(exports, "DEFAULT_BREEZE_PATH", { enumerable: true, get: function () { return Constants_1.DEFAULT_BREEZE_PATH; } });
Object.defineProperty(exports, "strNotSpecified", { enumerable: true, get: function () { return Constants_1.strNotSpecified; } });
var Envelope_1 = require("./Telemetry/Common/Envelope");
Object.defineProperty(exports, "Envelope", { enumerable: true, get: function () { return Envelope_1.Envelope; } });
var Event_1 = require("./Telemetry/Event");
Object.defineProperty(exports, "Event", { enumerable: true, get: function () { return Event_1.Event; } });
var Exception_1 = require("./Telemetry/Exception");
Object.defineProperty(exports, "Exception", { enumerable: true, get: function () { return Exception_1.Exception; } });
var Metric_1 = require("./Telemetry/Metric");
Object.defineProperty(exports, "Metric", { enumerable: true, get: function () { return Metric_1.Metric; } });
var PageView_1 = require("./Telemetry/PageView");
Object.defineProperty(exports, "PageView", { enumerable: true, get: function () { return PageView_1.PageView; } });
var RemoteDependencyData_1 = require("./Telemetry/RemoteDependencyData");
Object.defineProperty(exports, "RemoteDependencyData", { enumerable: true, get: function () { return RemoteDependencyData_1.RemoteDependencyData; } });
var Trace_1 = require("./Telemetry/Trace");
Object.defineProperty(exports, "Trace", { enumerable: true, get: function () { return Trace_1.Trace; } });
var PageViewPerformance_1 = require("./Telemetry/PageViewPerformance");
Object.defineProperty(exports, "PageViewPerformance", { enumerable: true, get: function () { return PageViewPerformance_1.PageViewPerformance; } });
var Data_1 = require("./Telemetry/Common/Data");
Object.defineProperty(exports, "Data", { enumerable: true, get: function () { return Data_1.Data; } });
var SeverityLevel_1 = require("./Interfaces/Contracts/SeverityLevel");
Object.defineProperty(exports, "SeverityLevel", { enumerable: true, get: function () { return SeverityLevel_1.SeverityLevel; } });
var IConfig_1 = require("./Interfaces/IConfig");
Object.defineProperty(exports, "ConfigurationManager", { enumerable: true, get: function () { return IConfig_1.ConfigurationManager; } });
var ContextTagKeys_1 = require("./Interfaces/Contracts/ContextTagKeys");
Object.defineProperty(exports, "ContextTagKeys", { enumerable: true, get: function () { return ContextTagKeys_1.ContextTagKeys; } });
var DataSanitizer_1 = require("./Telemetry/Common/DataSanitizer");
Object.defineProperty(exports, "dataSanitizeKeyAndAddUniqueness", { enumerable: true, get: function () { return DataSanitizer_1.dataSanitizeKeyAndAddUniqueness; } });
Object.defineProperty(exports, "dataSanitizeKey", { enumerable: true, get: function () { return DataSanitizer_1.dataSanitizeKey; } });
Object.defineProperty(exports, "dataSanitizeString", { enumerable: true, get: function () { return DataSanitizer_1.dataSanitizeString; } });
Object.defineProperty(exports, "dataSanitizeUrl", { enumerable: true, get: function () { return DataSanitizer_1.dataSanitizeUrl; } });
Object.defineProperty(exports, "dataSanitizeMessage", { enumerable: true, get: function () { return DataSanitizer_1.dataSanitizeMessage; } });
Object.defineProperty(exports, "dataSanitizeException", { enumerable: true, get: function () { return DataSanitizer_1.dataSanitizeException; } });
Object.defineProperty(exports, "dataSanitizeProperties", { enumerable: true, get: function () { return DataSanitizer_1.dataSanitizeProperties; } });
Object.defineProperty(exports, "dataSanitizeMeasurements", { enumerable: true, get: function () { return DataSanitizer_1.dataSanitizeMeasurements; } });
Object.defineProperty(exports, "dataSanitizeId", { enumerable: true, get: function () { return DataSanitizer_1.dataSanitizeId; } });
Object.defineProperty(exports, "dataSanitizeInput", { enumerable: true, get: function () { return DataSanitizer_1.dataSanitizeInput; } });
Object.defineProperty(exports, "dsPadNumber", { enumerable: true, get: function () { return DataSanitizer_1.dsPadNumber; } });
var TelemetryItemCreator_1 = require("./TelemetryItemCreator");
Object.defineProperty(exports, "TelemetryItemCreator", { enumerable: true, get: function () { return TelemetryItemCreator_1.TelemetryItemCreator; } });
Object.defineProperty(exports, "createTelemetryItem", { enumerable: true, get: function () { return TelemetryItemCreator_1.createTelemetryItem; } });
var PartAExtensions_1 = require("./Interfaces/PartAExtensions");
Object.defineProperty(exports, "CtxTagKeys", { enumerable: true, get: function () { return PartAExtensions_1.CtxTagKeys; } });
Object.defineProperty(exports, "Extensions", { enumerable: true, get: function () { return PartAExtensions_1.Extensions; } });
var Enums_1 = require("./Enums");
Object.defineProperty(exports, "DistributedTracingModes", { enumerable: true, get: function () { return Enums_1.DistributedTracingModes; } });
Object.defineProperty(exports, "EventPersistence", { enumerable: true, get: function () { return Enums_1.EventPersistence; } });
var HelperFuncs_1 = require("./HelperFuncs");
Object.defineProperty(exports, "stringToBoolOrDefault", { enumerable: true, get: function () { return HelperFuncs_1.stringToBoolOrDefault; } });
Object.defineProperty(exports, "msToTimeSpan", { enumerable: true, get: function () { return HelperFuncs_1.msToTimeSpan; } });
Object.defineProperty(exports, "getExtensionByName", { enumerable: true, get: function () { return HelperFuncs_1.getExtensionByName; } });
Object.defineProperty(exports, "isCrossOriginError", { enumerable: true, get: function () { return HelperFuncs_1.isCrossOriginError; } });
var applicationinsights_core_js_1 = require("@microsoft/applicationinsights-core-js");
Object.defineProperty(exports, "isBeaconApiSupported", { enumerable: true, get: function () { return applicationinsights_core_js_1.isBeaconsSupported; } });
Object.defineProperty(exports, "ITraceParent", { enumerable: true, get: function () { return applicationinsights_core_js_1.ITraceParent; } });
Object.defineProperty(exports, "createTraceParent", { enumerable: true, get: function () { return applicationinsights_core_js_1.createTraceParent; } });
Object.defineProperty(exports, "parseTraceParent", { enumerable: true, get: function () { return applicationinsights_core_js_1.parseTraceParent; } });
Object.defineProperty(exports, "isValidTraceId", { enumerable: true, get: function () { return applicationinsights_core_js_1.isValidTraceId; } });
Object.defineProperty(exports, "isValidSpanId", { enumerable: true, get: function () { return applicationinsights_core_js_1.isValidSpanId; } });
Object.defineProperty(exports, "isValidTraceParent", { enumerable: true, get: function () { return applicationinsights_core_js_1.isValidTraceParent; } });
Object.defineProperty(exports, "isSampledFlag", { enumerable: true, get: function () { return applicationinsights_core_js_1.isSampledFlag; } });
Object.defineProperty(exports, "formatTraceParent", { enumerable: true, get: function () { return applicationinsights_core_js_1.formatTraceParent; } });
Object.defineProperty(exports, "findW3cTraceParent", { enumerable: true, get: function () { return applicationinsights_core_js_1.findW3cTraceParent; } });
Object.defineProperty(exports, "findAllScripts", { enumerable: true, get: function () { return applicationinsights_core_js_1.findAllScripts; } });
var DomHelperFuncs_1 = require("./DomHelperFuncs");
Object.defineProperty(exports, "createDomEvent", { enumerable: true, get: function () { return DomHelperFuncs_1.createDomEvent; } });
var StorageHelperFuncs_1 = require("./StorageHelperFuncs");
Object.defineProperty(exports, "utlDisableStorage", { enumerable: true, get: function () { return StorageHelperFuncs_1.utlDisableStorage; } });
Object.defineProperty(exports, "utlEnableStorage", { enumerable: true, get: function () { return StorageHelperFuncs_1.utlEnableStorage; } });
Object.defineProperty(exports, "utlCanUseLocalStorage", { enumerable: true, get: function () { return StorageHelperFuncs_1.utlCanUseLocalStorage; } });
Object.defineProperty(exports, "utlGetLocalStorage", { enumerable: true, get: function () { return StorageHelperFuncs_1.utlGetLocalStorage; } });
Object.defineProperty(exports, "utlSetLocalStorage", { enumerable: true, get: function () { return StorageHelperFuncs_1.utlSetLocalStorage; } });
Object.defineProperty(exports, "utlRemoveStorage", { enumerable: true, get: function () { return StorageHelperFuncs_1.utlRemoveStorage; } });
Object.defineProperty(exports, "utlCanUseSessionStorage", { enumerable: true, get: function () { return StorageHelperFuncs_1.utlCanUseSessionStorage; } });
Object.defineProperty(exports, "utlGetSessionStorageKeys", { enumerable: true, get: function () { return StorageHelperFuncs_1.utlGetSessionStorageKeys; } });
Object.defineProperty(exports, "utlGetSessionStorage", { enumerable: true, get: function () { return StorageHelperFuncs_1.utlGetSessionStorage; } });
Object.defineProperty(exports, "utlSetSessionStorage", { enumerable: true, get: function () { return StorageHelperFuncs_1.utlSetSessionStorage; } });
Object.defineProperty(exports, "utlRemoveSessionStorage", { enumerable: true, get: function () { return StorageHelperFuncs_1.utlRemoveSessionStorage; } });
Object.defineProperty(exports, "utlSetStoragePrefix", { enumerable: true, get: function () { return StorageHelperFuncs_1.utlSetStoragePrefix; } });
var UrlHelperFuncs_1 = require("./UrlHelperFuncs");
Object.defineProperty(exports, "urlParseUrl", { enumerable: true, get: function () { return UrlHelperFuncs_1.urlParseUrl; } });
Object.defineProperty(exports, "urlGetAbsoluteUrl", { enumerable: true, get: function () { return UrlHelperFuncs_1.urlGetAbsoluteUrl; } });
Object.defineProperty(exports, "urlGetPathName", { enumerable: true, get: function () { return UrlHelperFuncs_1.urlGetPathName; } });
Object.defineProperty(exports, "urlGetCompleteUrl", { enumerable: true, get: function () { return UrlHelperFuncs_1.urlGetCompleteUrl; } });
Object.defineProperty(exports, "urlParseHost", { enumerable: true, get: function () { return UrlHelperFuncs_1.urlParseHost; } });
Object.defineProperty(exports, "urlParseFullHost", { enumerable: true, get: function () { return UrlHelperFuncs_1.urlParseFullHost; } });
var Offline_1 = require("./Offline");
Object.defineProperty(exports, "createOfflineListener", { enumerable: true, get: function () { return Offline_1.createOfflineListener; } });
exports.PropertiesPluginIdentifier = "AppInsightsPropertiesPlugin";
exports.BreezeChannelIdentifier = "AppInsightsChannelPlugin";
exports.AnalyticsPluginIdentifier = "ApplicationInsightsAnalytics";
