export declare const UNDEFINED_VALUE: any;
export declare const STR_EMPTY = "";
export declare const STR_CHANNELS = "channels";
export declare const STR_CORE = "core";
export declare const STR_CREATE_PERF_MGR = "createPerfMgr";
export declare const STR_DISABLED = "disabled";
export declare const STR_EXTENSION_CONFIG = "extensionConfig";
export declare const STR_EXTENSIONS = "extensions";
export declare const STR_PROCESS_TELEMETRY = "processTelemetry";
export declare const STR_PRIORITY = "priority";
export declare const STR_EVENTS_SENT = "eventsSent";
export declare const STR_EVENTS_DISCARDED = "eventsDiscarded";
export declare const STR_EVENTS_SEND_REQUEST = "eventsSendRequest";
export declare const STR_PERF_EVENT = "perfEvent";
export declare const STR_OFFLINE_STORE = "offlineEventsStored";
export declare const STR_OFFLINE_SENT = "offlineBatchSent";
export declare const STR_OFFLINE_DROP = "offlineBatchDrop";
export declare const STR_GET_PERF_MGR = "getPerfMgr";
export declare const STR_DOMAIN = "domain";
export declare const STR_PATH = "path";
export declare const STR_NOT_DYNAMIC_ERROR = "Not dynamic - ";
export declare const STR_REDACTED = "REDACTED";
export declare const DEFAULT_SENSITIVE_PARAMS: string[];
