// -----------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

import { IDynamicValuePreference } from './dataHelpers';

export const dynamicValuePreferences: IDynamicValuePreference[] = [
  { name: 'triggerType' },
  { name: 'staticMessage' },
  { name: 'embedVideoCoreState' },
  { name: 'authState' },
  { name: 'newState' },
  // tslint:disable-next-line:no-any
  { name: 'message', converter: (value: any) => value.replace('<safe>', '').replace('</safe>', '') },
  // tslint:disable-next-line:no-any
  { name: 'durationMs', converter: (value: any) => `${Math.trunc(value)} ms` },
  { name: 'videoState' }
];

export const valuesToExcludeFromCondensedList: string[] = [
  'baseData',
  'browserTimingMethod',
  'standardContextVersion',
  'isDevelopmentMode',
  'app',
  'userId',
  'clientSessionId',
  'userSessionId',
  'tenantId',
  'servicePlan',
  'userType',
  'videoId',
  'isPublicAnonymous',
  'isFastEmbed',
  'deferredLoad',
  'client',
  'playbackSessionId',
  'buildNumber',
  'deploymentRing',
  'clusterRegion',
  'clusterIdentity',
  'serviceRegion',
  'apiGatewayUri',
  'apiGatewayVersion',
  'azureMediaPlayerVersion',
  'isEmbed',
  'isDebugLoggingEnabled',
  'expContext',
  'viewContext',
  'UserAgent',
  'language',
  'region',
  'isLive',
  'currentVolume',
  'previousVolume',
  'presentationTimeOffsetInSec',
  'playerSourceResetCount',
  'currentAudioTrackName',
  'ieAudioIsDisabled',
  'contentType',
  'contentSource',
  'encodingProfile',
  'creatorApp',
  'GOPSize',
  'isUpdated',
  'isDeleted',
  'isPageVisible',
  'sdnName',
  'msToVideoStart',
  'playedSeconds',
  'fullscreenTime',
  'duration',
  'suspendedTriggered',
  'enteredFullscreen',
  'loadTimeMs',
  'seekCount',
  'seekTimeTotal',
  'maxSeekTime',
  'avgSeekTime',
  'Br_0Kbps_300Kbps',
  'Br_300Kbps_500Kbps',
  'Br_500Kbps_1Mbps',
  'Br_1Mbps_1_5Mbps',
  'Br_1_5Mbps_3Mbps',
  'Br_3Mbps_5Mbps',
  'Br_5Mbps_6Mbps',
  'Br_6Mbps_20Mbps',
  'Br_20Mbps_above',
  'Pr_2_0',
  'Pr_1_75',
  'Pr_1_5',
  'Pr_1_25',
  'Pr_1_0',
  'Pr_0_5',
  'CurrentPlaybackRate',
  'uniquePlayTime',
  'qoeRebufferingScore',
  'currentBufferedLength',
  'currentAudioBufferLength',
  'currentVideoBufferLength',
  'currentDownloadBitrate',
  'perceivedBandwidth',
  'isInAudioOnlyMode',
  'displayedAudioOnlyMessage',
  'qoeRebuffering',
  'playIntervals',
  'uniquePlayIntervals',
  'MimeType',
  'maxVideoResolution',
  'loaded',
  'StreamId',
  'PluginVersion',
  'PlayerVersion',
  'PlaybackTech',
  'ProtectionType',
  'autoPlay',
  'heuristicsProfile',
  'isBehindCDN',
  'manualBitrateChanged',
  'isCyclePresent',
  'groupings'
];
