name: 'Stale issue handler'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'

permissions:
  actions: write
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@4391f3da665fdf50b6810c1a66712fb9ba21aa93 # v11.0.0
        id: stale
        with:
          stale-issue-message: 'This Issue will be closed in 30 days. Please remove the "Stale" label or comment to avoid closure with no action.'
          stale-pr-message: 'This PR will be closed in 30 days. Please remove the "Stale" label or comment to avoid closure with no action.'
          operations-per-run: 200
          days-before-stale: 300
          days-before-close: 30
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          close-issue-label: 'closed'
          close-pr-label: 'closed'
          exempt-issue-labels: 'bug,enhancement,documentation,waiting,keep'
          exempt-pr-labels: 'waiting,keep'
          include-only-assigned: true